//
// Created by Jason Justman on 8/18/20.
//

#include <jni.h>

#ifndef LIBATSC3_ANDROID_SAMPLE_APP_W_PHY_ATSC3NDKPHYVIRTUALSTATICJNILOADER_H
#define LIBATSC3_ANDROID_SAMPLE_APP_W_PHY_ATSC3NDKPHYVIRTUALSTATICJNILOADER_H
JavaVM* atsc3_ndk_phy_virtual_static_loader_get_javaVM();

#endif //LIBATSC3_ANDROID_SAMPLE_APP_W_PHY_ATSC3NDKPHYVIRTUALSTATICJNILOADER_H

