//
// Created by Jason Justman on 8/19/20.
//

#include <jni.h>

#ifndef LIBATSC3_ANDROID_SAMPLE_APP_W_PHY_ATSC3NDKPHYCLIENTBASE_H
#define LIBATSC3_ANDROID_SAMPLE_APP_W_PHY_ATSC3NDKPHYCLIENTBASE_H
#include <atsc3_utils.h>

#endif //LIBATSC3_ANDROID_SAMPLE_APP_W_PHY_ATSC3NDKPHYCLIENTBASE_H
