//
// Created by Jason Justman on 8/10/20.
//

#ifndef LIBATSC3_ANDROID_SAMPLE_APP_NO_PHY_ATSC3NDKPHYBRIDGECLIENT_H
#define LIBATSC3_ANDROID_SAMPLE_APP_NO_PHY_ATSC3NDKPHYBRIDGECLIENT_H
#include "Atsc3JniEnv.h"

#include "Atsc3NdkPHYBridge.h"

class Atsc3NdkPHYBridgeClient {
    public:

};

#endif //LIBATSC3_ANDROID_SAMPLE_APP_NO_PHY_ATSC3NDKPHYBRIDGECLIENT_H
